apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-llm-chroma
spec:
  storageClassName: rook-ceph-block-tide
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
